" Configuration file for vim
set modelines=0		" CVE-2007-2438

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set backspace=2		" more powerful backspacing

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup nobackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup nobackup

set clipboard=unnamed

" Show line numbers
set number

" Syntax highlight
syntax on

" Highlight search result
set hlsearch

" Show row and column ruler information
set ruler

" Show mode
set showmode

" Set comment color
highlight Comment ctermfg=cyan

" Set search result color
highlight Search term=reverse ctermbg=4 ctermfg=7

" Auto intdent
set autoindent
" Smart indent
set smartindent
" Number of auto-indent space
set shiftwidth=2

" Use space instead of tab
set expandtab
" Set number space per tab
set tabstop=2

" remap ESC to terminal mode
:tnoremap <Esc> <C-\><C-n>